export const APPLICANT_ROUTES_PREFIX = "/applicant";
export const APPLICANT_ROUTES = {
  PROFILE: `${APPLICANT_ROUTES_PREFIX}/details`, //TODO: change the route
  ALL_JOBS: `${APPLICANT_ROUTES_PREFIX}/job-listing`,
  MY_JOBS: `${APPLICANT_ROUTES_PREFIX}/my-jobs`,
  CREATE_AND_EDIT_PROFILE: `${APPLICANT_ROUTES_PREFIX}/create-profile`,
  JOB_DETAILS: `${APPLICANT_ROUTES_PREFIX}/job-details`,
  JOB_STATUS: `${APPLICANT_ROUTES_PREFIX}/job-status`,
  CHATS: `${APPLICANT_ROUTES_PREFIX}/chats`,
  PLANS: `${APPLICANT_ROUTES_PREFIX}/plans`,
};
